export const CATEGORY_DETAILS_DEFAULT_PAGE = 1;
export const CATEGORY_DETAILS_DEFAULT_LIMIT = 12;
export const CATEGORY_DETAILS_DEFAULT_TOTAL = 0;
export const CATEGORY_DETAILS_DEFAULT_TOTAL_PAGES = 1;
